---
title: "dimesionnality reduction"
author: "Dr. ASRI"
date: "2023-05-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## packages

```{r include=FALSE}
library(tidyverse)
library(tidymodels)
library(tidytext)
library(Rtsne)
library(embed)
library(readxl)
library(tidyclust)
```

## données

```{r}
data <- read_excel("D:/Downloads/File For Challenge Open Data.xlsx")
```

## cleaning

```{r}
data <- data  %>% 
  select(-c(Id, WILAYA))
```

```{r}

binary <- sapply(names(data),
                 function (x) ifelse(length(unique(data[[x]]))==2,x,NA)) %>%
  na.omit()

data <- data %>% mutate_at(binary,~ as.numeric(. %in% c("O","Femme")))
```

```{r}
data$Q7_A5 <- match(data$Q7_A5, c("Aucune", unique(data$Q7_A5)))
data <- data %>%
  mutate(Q7_A5 = Q7_A5-1) %>%
  mutate(Q7_A6 = ifelse(Q7_A6=="NSP",NA,Q7_A6)) %>%
  mutate_if(is.character,as.factor)
```

## t-SNE

```{r}
set.seed(123)
```

```{r}
rec <- recipe(~., data = data) %>%
  step_impute_knn(all_predictors(),neighbors = 5) %>%
  step_dummy(all_nominal())

data <- rec %>% prep(data) %>% juice()
```

Hiarcical cluster

```{r}
df <- distinct(data)
sample <- df %>% sample_n(size = 600)

hc_spec <- hier_clust(linkage_method = "complete")

hc_fit <- hc_spec %>%
fit(~.,data = sample)

hc_fit$fit %>% plot()
```

K-modes

```{r eval=FALSE, include=FALSE}
kmodes_spec <- klaR::kmodes(df,3)



kmodes_spec$cluster -> cluster
```

k-means

```{r}
k_means_spec <- k_means(num_clusters = 4) %>% set_engine("stats")

kmeans_workflow <- workflow() %>%
add_model(k_means_spec) %>% add_formula(~.)

kmeans_fit <- kmeans_workflow %>%
fit(data = df)

clustered <- augment(kmeans_fit, new_data = df)
```

```{r include=FALSE}
library(keras)
library(Rtsne)
library(plotly)
```

```{r}
tsne <- Rtsne(df, 
              perplexity = 30,
              max_iter = 500,dim = 3)

```

### 3-d graphes

```{r}

plotly_df <- as_tibble(tsne$Y) %>% 
  cbind(clustered$.pred_cluster) %>% 
  mutate(labels = clustered$.pred_cluster) %>% 
  mutate(labels = as.factor(labels))

plot_ly(plotly_df, x = ~V1, y = ~V2, z = ~V3, color = ~labels) %>% 
  add_markers()

```
