---
title: "Pca regression"
author: "Tata iles"
date: "2023-04-10"
output: html_document
---

```{r}
library(tidyverse)
library(corrplot)
```

# Simulation des variables

$y = c + 0.5x1 + 0.23x2 + 0.73x3 + \epsilon$

```{r}
set.seed(123)
x1 <- rnorm(1000, mean = 5, sd = 2)
x2 <- x1 + rnorm(1000, mean = 0, sd = 0.2)
x3 <- rnorm(1000, mean = 5.5, sd = 4.3)
e <- rnorm(1000, 0, 1)
c <- runif(1,min = 1 ,max = 5)

y <- c + 0.5*x1 + 0.23*x2 + 0.73*x3 + e


data <- data.frame(x1, x2, x3, y)
data %>% head(5)
```

# Correlation

```{r}
data %>% cor() %>% corrplot(type = "upper",method = "circle",  addCoef.col = "red")
```

# Regression linéare simple

```{r}
data %>% lm(y ~ . , data=.) %>% summary()
```

# PCA

```{r}
pca <- data %>% select(-3) %>% prcomp(center = TRUE, scale. = TRUE)
```

```{r}
pca %>% summary()
```

```{r}
pca %>% screeplot(type = "l")
```

# PCA regression

```{r}
PC1 <- pca$x[,1]
PC2 <- pca$x[,2]


pca_reg <- lm(y ~ PC1 + PC2)

pca_reg %>% summary()
```

# Exemple d'une base de données réelle

```{r message=FALSE, warning=FALSE}
library(readr)
df <- read_csv("D:/Python-R/Databases/Life Expectancy Data for PCR.csv")

df <- df %>% na.omit()

df <- df %>% select(-c("Country","Year","Status"))

df %>% head()
```

```{r}
df %>% cor() %>%
  corrplot(tl.cex = 0.7, cl.cex = 0.01,type = "upper")
```

```{r}
df %>% lm(`Life expectancy` ~ ., data = .) %>% summary()
```

```{r}
pcr <- df %>% select(-`Life expectancy`) %>% prcomp(scale = TRUE)

pcr %>% screeplot(type = "l", main="Screeplot for Life expectancy")
```

```{r}
p <- function(min, max){
  i <- min
  new_data <-data.frame(pcr$x[,i])
  while (i < max) {
    new_data <- cbind(new_data,data.frame(pcr$x[,i+1]))
    i <- i+1
  } 
  
  return(new_data)
}

p(1,5) -> new_df
```

```{r}
new_df <- cbind(df$`Life expectancy`,new_df)
colnames(new_df) <- c("life.expectancy","pc1","pc2","pc3","pc4","pc5")

new_df%>% head(5)
```

```{r}
new_df %>% lm(life.expectancy ~ ., data=.) %>% summary()

```
